### ISSUE TITLE
Project Peer Review

### ISSUE THREAD

**Issue by SebasRSoler** [Santiagoooooo/TermProject#2]
i. Technical issues/bugs

1. Some page options in the navigation bar (Pokédex) do not link to another page.
2. Some pictures have issues and do not appear on the page. 
3. Pokémon Games and Pokémon TV shows and movie pages do not appear in the navigation bar, only in the sitemap. 

ii. Suggestions on Content

1. Add additional pages with content to the website, including the Pokédex page. 
2. The home page is clustered with a lot of text and pictures. Content could be distributed among other pages on the website. 
3. Use the same text font and family throughout all the pages.
  

Overall, amazing styling and content!

**Comment by Santiagoooooo** [comment]
> i. Technical issues/bugs
> 
> 1. Some page options in the navigation bar (Pokédex) do not link to another page.
> 2. Some pictures have issues and do not appear on the page.
> 3. Pokémon Games and Pokémon TV shows and movie pages do not appear in the navigation bar, only in the sitemap.
> 
> ii. Suggestions on Content
> 
> 1. Add additional pages with content to the website, including the Pokédex page.
> 2. The home page is clustered with a lot of text and pictures. Content could be distributed among other pages on the website.
> 3. Use the same text font and family throughout all the pages.
> 
> Overall, amazing styling and content!

Thank you so much for giving me feedback and suggestion! I'll re-design my home page because I also think it's kinda messy. For the Pokédex, I'm still developing it, as well as the Merchandise page. The reason why I do not put tv shows and games on the top nav bar is that I want to put the most important/attractive page on it, so I put those into sitemap instead. Thanks for your feedback again!
